version: "3"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n@sha256:6eaa815beb29b0398860250b587a62f09b62f1b30eeb1612830b500f84a737d6
    ports:
    - "5678:5678"
    container_name: n8n
    restart: always
    volumes:
    - n8n_data:/home/node/.n8n
    environment:
    - WEBHOOK_URL=https://flow.kemet.ch

volumes:
  n8n_data:

