version: '3'

services:
  directus:
    image: directus/directus@sha256:b213944fb16e99e0554f52ade9252c89f481454d09746d4319ab7e097fdf585a
    container_name: Directus
    restart: always
    ports:
      - 8055:8055
    volumes:
      - directus_uploads_data:/directus/uploads
      - directus_database_data:/directus/database
    env_file:
      - .env
    environment:
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

volumes:
  directus_uploads_data:
  directus_database_data:
