version: "3"

services:
  freshrss:
    image: freshrss/freshrss:1.21.0-alpine
    container_name: FreshRSS 
    restart: always
    logging:
      options:
        max-size: 10m
    ports:
      - "8001:80"
    environment:
      CRON_MIN: '1,31'
      TZ: Europe/Paris
      LISTEN: 0.0.0.0:80
    volumes:
      - freshrss_data:/var/www/FreshRSS/data

volumes:
  freshrss_data:

