---

- name: Set hostname
  ansible.builtin.hostname:
    name: kemet.ch

- name: Install required system packages
  ansible.builtin.apt: 
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest 
    update_cache: true
