version: "3"

services:
  uptime:
    image: louislam/uptime-kuma:1
    container_name: Uptime-Kuma
    ports:
    - "3001:3001"
    restart: always
    volumes:
    - uptime-kuma:/app/data

volumes:
  uptime-kuma:
