version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
    - "9000:9000"
    container_name: Portainer
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data

volumes:
  portainer_data:

