---
hostname: oliverbucher.ch

proxies:
  - url: oliverbucher.ch
    service: demo:8000
  - url: ls.oliverbucher.ch
    service: portainer:9000
  - url: monitor.oliverbucher.ch
    service: grafana:3000

projects:
  - demo
  - portainer
  - monitoring
