---

- hosts: all
  become: true
  vars_files:
    - ./vars.yml
    - "./{{ tag }}-vars.yml"
  vars:
    - ansible_port: "{{ new_ssh_port }}"
  roles:
    - role: firewall
      tags: firewall 
    - role: upgrades
      tags: upgrades 
    - role: container
      tags: container 
    - role: reverse-proxy
      tags: reverse-proxy
    - role: projects
      tags: projects
