version: "3"

services:
  uptime:
    image: louislam/uptime-kuma@sha256:1630eb7859c5825a1bc3fcbea9467ab3c9c2ef0d98a9f5f0ab0aec9791c027e8
    container_name: Uptime-Kuma
    ports:
    - "3001:3001"
    restart: always
    volumes:
    - uptime-kuma:/app/data

volumes:
  uptime-kuma:
