---

- name: Create project folders
  ansible.builtin.file:
    path: "/projects/{{ item }}/"
    state: directory
  loop: "{{ projects }}"

- name: Add files
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "/projects/{{ item }}/"
  register: p
  loop: "{{ projects }}"

- name: Tear down existing containers
  community.docker.docker_compose:
    project_src: "/projects/{{ item.item }}/"
    state: absent
  when: item.changed
  loop: "{{ p.results }}"

- name: Build and start service
  community.docker.docker_compose:
    project_src: "/projects/{{ item.item }}/"
  when: item.changed
  loop: "{{ p.results }}"
