---
- hosts: all
  become: true
  roles:
    - role: init
      tags: init
    - role: docker
      tags: docker
    - role: caddy
      tags: caddy
    - role: dc-portainer
      tags: 
      - container
      - portainer
    - role: dc-uptime-kurma
      tags: 
      - container
      - uptime

