---
- hosts: all
  become: true
  #  gather_facts: no 

  #  vars:
  #    key_source: ./vault/
  #    key_dest: "{{ lookup('env', 'HOME') }}/.ssh/"
  #
  #  pre_tasks:
  #    - name: Ensure SSH directory exists.
  #      ansible.builtin.file:
  #        dest: "{{ key_dest | dirname }}"
  #        mode: 0700
  #        owner: "{{ ansible_user }}" 
  #        state: directory
  #      delegate_to: 127.0.0.1
  #    - name: Install SSH key
  #      ansible.builtin.copy:
  #        src: "{{ key_source }}/id_rsa"
  #        dest: "{{ key_dest | dirname }}/id_rsa"
  #        mode: 0600
  #        owner: "{{ ansible_user }}" 
  #    - name: Gathering facts 
  #      setup:
  #
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: kemet.ch

    - name: Install required system packages
      ansible.builtin.apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker and Docker Compose Module for Python
      ansible.builtin.pip:
        name: "{{ item }}"
      loop: [ 'docker', 'docker-compose' ]

  #  post_tasks:
  #    - name: Lock SSH key "{{ ssh_key_file }}"
  #      ansible.builtin.command: ssh-add -d "{{ ssh_key_file }}"
  #      delegate_to: 127.0.0.1
  #      become: no
  #      changed_when: no
